import { COLOR_SCHEMA } from "../../../constants/styles/main"

const COLORS = {
  ACCORDION_TEXT: `${COLOR_SCHEMA.BASIC.WHITE}`,
  BACKGROUND: `${COLOR_SCHEMA.PRIMARY.SECONDARY_BLUE}`,
  DROPDOWN_HOVER: `${COLOR_SCHEMA.PRIMARY.PRIMARY_BLUE}`,
  DROPDOWN_TEXT: `${COLOR_SCHEMA.BASIC.WHITE}`,
}

export default COLORS
